config/routes.rb
Rails.application.routes.draw do

   root 'users#index'

   delete 'sessions/destroy' => 'sessions#destroy'
   get "users/check_email" => 'users#check_email'
   get "sessions/check_email" => 'sessions#check_email'
   get "sessions/check_password" => 'sessions#check_password'

   get '/auth/:provider/callback', to: 'sessions#create'
   get '/auth/failure', to: redirect('/')
   get 'sign_out', to: 'sessions#destroy', as: 'sign_out'

    resources :users
    resources :sessions

    resources :events do
      member do
        get 'email_response'
      end
    end

end

app/models/event.rb
class Event < ActiveRecord::Base

	has_many :users,through: :invitees
	has_many :invitees
	belongs_to :user

	validates :event_name,
	:presence =>true,
	:length => {:minimum => 1,:maximum => 30}

	validates :venue,
	:presence =>true,
	:length => {:minimum => 1,:maximum => 30}

	validates :date,
	:presence =>true

	validates :description,
	:presence =>true

	validates :status,
	:presence =>true


	def addInvitees(user_id,event_id,current_user)
		user_id.each do |id|
			@invitee = Invitee.new(user_id: id, event_id: event_id)
			@invitee.save
			@creator = current_user.name
			InviteMailer.send_email(@invitee, @creator).deliver
		end
	end

	def selectInvitee(event)
		Invitee.where(event_id: event).pluck(:user_id)
	end

	def check_update(old_event,new_event)
		if old_event.description!=new_event[:description]||old_event.venue!=new_event[:venue]||old_event.date.to_s!=new_event[:date]||old_event.time.strftime('%X')+".000"!=new_event[:time]

			UpdateMail.update_event(old_event,new_event).deliver
		end
	end

	def notparticipants(event1)
		@user=User.all()
		if Invitee.where(event_id: event1).pluck(:user_id).blank?
			@user.all
		else
			@user.where('id not in (?)',Invitee.where(event_id: event1).pluck(:user_id))
		end
	end
end

app/models/invitee.rb
class Invitee < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :events, through: :invitees
	has_many :invitees
	has_secure_password :validations => false


	validates :name,
	:presence =>true,
	:length => {:minimum => 1,:maximum => 50},
	:format => {:with => ConfigCenter::GeneralValidations::NAME_FORMAT_REG_EXP},
	:unless => proc{|u| u.provider.present?}

	validates :email,
	:presence =>true,
	:format => {:with =>ConfigCenter::GeneralValidations::EMAIL_FORMAT_REG_EXP },
	:unless => proc{|u| u.provider.present?}

	validates :password,
	:presence =>true,
	:length => {:minimum => 6 },                       
	:unless => proc{|u| u.provider.present?}

	mount_uploader :image, ImageUploader

	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_digest == BCrypt::Engine.hash_secret(password, user.password_digest)
			user
		else
			nil
		end
	end		

	def self.create_with_omniauth(auth)
		create! do |user|
			user.provider = auth["provider"]
			user.uid = auth.uid
			user.name = auth.info.name
			user.email = auth.uid+"@twitter.com"
			user.save!
		end
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  before_filter :set_cache_buster

  private
  def current_user
  	current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_login
    unless session[:user_id]
      redirect_to root_path
      flash[:error] = "You must be logged in to access the section!"
    end
  end

  def set_cache_buster
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end

  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_filter :require_login, :except =>[:email_response]

	def new
		@event=Event.new
		respond_to do |format|
			format.js{}
		end
	end

	def show

		@users=User.all
		@event= Event.find(params[:id])
		@invitee=Invitee.where(event_id:@event)
		@participants=@event.selectInvitee(@event.id)
		respond_to do |format|
			format.js{}
		end
	end

	def email_response
		@invitee = Invitee.find_by_id(params[:id])
		@response = params[:response]
		if @invitee.valid?
			@invitee.response=@response
			@invitee.save
			redirect_to root_path,:notice =>" Thank you for RSVP"
		end
	end

	def create
		@event=Event.new(event_params)
		@event.user_id=current_user.id
		if @event.valid? && @event.errors.blank?
			@event.save
			if params["invitees"].present?
				@event.addInvitees(params["invitees"],@event.id,current_user)
			end
			respond_to do |format|
				format.html{
					redirect_to events_path,:notice => "Event Created!"
				}
			end
		else
			redirect_to events_path, :notice => "Event cannot be Created!"
		end
	end

	def index
		@users=User.all
		@events = Event.order("updated_at desc").page(params[:page]).per(5)
		@events.each do|event|
			if event.present?	
				@event=@events.first
				@participants=@event.selectInvitee(@event.id)
				@user=@event.notparticipants(@event.id)
			else
				redirect_to events_path, :notice => "No events"
			end
		end
	end

	def edit
		@users=User.all
		@event= Event.find(params[:id])
		@participants=@event.selectInvitee(@event.id)
		@user=@event.notparticipants(@event.id)
		respond_to do |format|
			format.js{}
		end
	end

	def update
		@event= Event.find(params[:id])
		if @event.valid? && @event.errors.blank?
			@event.check_update(@event,event_params)
			@event.update(event_params)
			if params["invitees"].present?
				@event.addInvitees(params["invitees"],@event.id,current_user)
			end
			respond_to do |format|
				format.html{
					redirect_to events_path,:notice => "Event Updated!"
				}
			end
		else
			redirect_to events_path, :notice => "Event cannot be Updated!"
		end
	end

	private

	def event_params
		params.require(:event).permit(:event_name, :venue, :date, :time, :description, :status)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	skip_before_filter :verify_authenticity_token

	def new
		respond_to do |format|
			format.js {}
		end
	end

	def check_email
		@user = User.find_by_email(params[:email])
		respond_to do |format|
			format.json { render :json => !!@user }
		end
	end

	def create
		if params[:provider] == "twitter"
			auth = request.env["omniauth.auth"]
			if User.find_by_uid(auth["extra"]["raw_info"]["id"]).present?
				user= User.find_by_uid(auth["extra"]["raw_info"]["id"])
			else
				user = auth.find_by_provider_and_uid(auth["provider"],
					auth["uid"]) || User.create_with_omniauth(auth)
			end
		else
			user = User.authenticate(params[:email], params[:password])
		end

		if user
			session[:user_id] = user.id
			redirect_to  events_path, :notice => "Logged in!"
			flash[:success]= "Successfully Logged In"
		else
			flash[:error]="Email id and password does not match"
			redirect_to root_path
		end
	end

	def index
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url, :notice => "Logged out!"

	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	skip_before_filter :verify_authenticity_token

	def new
		@user = User.new
		respond_to do |format|
			format.js{}
		end
	end

	def check_email
		@user = User.find_by_email(params[:user][:email])

		respond_to do |format|
			format.json { render :json => !@user }
		end
	end

	def create
		@user= User.new(user_params)
		if @user.valid? && @user.errors.blank?
			@user.save
			session[:user_id] = @user.id
			respond_to do |format|

				format.html{
					redirect_to  events_path, :notice => "Signed up!"
				}
				format.js{
					redirect_to(events_path, :notice => 'Account created Successfully.')
				}
			end

		else
			redirect_to root_path, :notice => "error!"

		end

	end

	def index
	end

	private

	def user_params

		params.require(:user).permit(:name, :email, :password, :password_confirmation,:image)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/flash_helper.rb
module FlashHelper


  # This function will set a flash message depending up on the request type (ajax - xml http or direct http)
  # example : store_flash_message("The message has been sent successfully", :success)
  # FIXME - example, documention & spec # No need for documentation
  def store_flash_message(message, type)
    if request.xhr?
      flash.now[type] = message
    else
      flash[type] = message
    end
  end

end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_create_event.html.erb
<script type="text/javascript">
  var dateToday = new Date(); 
  $(function() {
   $( "#datepicker1" ).datepicker({ minDate: 0,dateFormat: 'yy-mm-dd'});
 });
</script>

<div class="row">
 <div class="col-sm-12">
  <div class="well">
   <%= form_for :event, :url => event_path(@event), :method=> :put,:html => {:class =>"form-horizontal",:id =>"event_form"} do |f| %>
   <!--Venue -->
   <div class="form-group">
     <label for="inputEvent" class="col-sm-3 control-label">Event*</label>
     <div class="col-sm-7">
      
      <%= f.text_field :event_name,:class =>"form-control", :id=>"event_name",:placeholder => "Event" , readonly: true %>
    </div>
    <div class="col-sm-2"></div>
  </div>
  <!--Venue -->
  <div class="form-group">
   <label for="inputVenue" class="col-sm-3 control-label">Venue</label>
   <div class="col-sm-7">
     <%= f.text_field :venue,:class =>"form-control", :id=>"venue_name",:placeholder => "Venue", readonly: true %>
   </div>
   <div class="col-sm-2"></div>
 </div>
 <!--Date and Time -->
 <div class="form-group">
   <label for="inputDate" class="col-sm-3 control-label">Date</label>
   <div class="col-sm-3">
    <%= f.text_field :date,:class =>"form-control", :id=>"venue_name",:id =>"datepicker1" ,:placeholder => "Date", readonly:(@event.user_id!=current_user.id) %>
  </div>
  <label for="inputTime" class="col-sm-1a control-label">Time</label>
  <div class="col-sm-3">
    <%= f.time_field :time,:class =>"form-control", :id=>"event_time",:placeholder => "Time" , readonly:(@event.user_id!=current_user.id)%>
  </div>
</div>
<!--Description -->
<div class="form-group">
 <label for="inputescription" class="col-sm-3 control-label">Description</label>
 <div class="col-sm-7">
  <%= f.text_area :description,:size=> "50x7",:class =>"form-control", :id=>"venue_name",:placeholder => "Venue" , readonly:(@event.user_id!=current_user.id)%>
</div>
<div class="col-sm-2"></div>
</div>
<!--Invited -->
<% if @event.user_id!=current_user.id %>
<div class="form-group">
 <label for="inputescription" class="col-sm-3 control-label">Invited</label>
 <div class="col-sm-7">
  <table class="table table-responsive table-fixed">
   <thead>
    <tr>
    </tr>
  </thead>
  <tbody style="border-style: solid;border-width: 1px;border-color: #ccc;">

   <!-- not current user's ticket -->
   
   <%participants.each do |user_id| %>
   <% users.each do |user|%>
   <% if user.id ==user_id%>
   <tr>
    <td><%=user.name.titleize%></td>
  </tr>
  <%end%>
  <%end%>
  <%end%>
  
</tbody>
</table>
</div>
<div class="col-sm-2"></div>
</div>


<%else%>


<div class="form-group">
 <label for="inputescription" class="col-sm-3 control-label">Invited</label>
 <div class="col-sm-7">
  <table class="table table-responsive table-fixed">
   <thead>
    <tr>
    </tr>
  </thead>
  <tbody style="border-style: solid;border-width: 1px;border-color: #ccc;">

   <!-- not current user's ticket -->
   
   <%participants.each do |user_id| %>
   <% users.each do |user|%>
   <% if user.id ==user_id%>
   <tr>
    <td><%=user.name.titleize%></td>
  </tr>
  <%end%>
  <%end%>
  <%end%>
  
</tbody>
</table>
</div>
<div class="col-sm-2"></div>
</div>

<!-- invite new users -->

<div class="form-group">
 <label for="inputescription" class="col-sm-3 control-label">Invite</label>
 <div class="col-sm-7">
  <table class="table table-responsive table-fixed">
   <thead>
    <tr>
    </tr>
  </thead>
  <tbody style="border-style: solid;border-width: 1px;border-color: #ccc;">

    <%@user=notparticipants%>
    <%if @user.present?%>
    <% @user.each do |user|%>
    <% unless user.id==current_user.id %>
    <tr>
      <td><%= check_box_tag "invitees[]", user.id %></td>
      <td><%=user.name.titleize%></td>
    </tr>
    <%end%>
    <%end%>
    <%else%>
    <tr>
      <th style="text-align:center;">No users left to invite</th>
    </tr>
    <%end%>

  </tbody>
</table>
</div>
<div class="col-sm-2"></div>
</div>
<%end%>


<!--Status -->
<div class="form-group">
 <label for="inputstatus" class="col-sm-3 control-label">Status</label>
 <div class="col-sm-3">
  <%= f.select :status, ['open','close'],{selected: @event.status}, {class: 'form-control1'}  %>
</div>
<div class="col-sm-2"></div>
</div>

<div class="modal-footer">
  <% if @event.user_id==current_user.id %>
  <%= f.submit "Ok", :class=>"btn btn-primary ok-btn-padding", :id =>"signup_button"%>
  
  <button type="button" class="btn btn-default ok-btn-padding" data-dismiss="modal">Cancel</button>
  <%end%>
  <%end%>
</div>
</div>
</div>
</div>

app/views/events/_create_event_modal.html.erb
<script type="text/javascript">
  var dateToday = new Date();
  $(function() {
   $( "#datepicker" ).datepicker({ minDate: 0,dateFormat: 'yy-mm-dd'});
 });
</script>

<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Create a New Event</h4>
    </div>
    <div class="modal-body"
    <!--Model body -->
    <div class="row">
     <div class="col-sm-12">
      <%= form_for :event, :url => events_path, :method=> 'post',:html => {:class =>"form-horizontal",:id =>"event_form"} do |f| %>

      <!--Venue -->
      <div class="form-group">
       <label for="inputEvent" class="col-sm-3 control-label">Event*</label>
       <div class="col-sm-7">

        <%= f.text_field :event_name,:class =>"form-control1", :id=>"event_name",:placeholder => "Event" %>
      </div>
      <div class="col-sm-2"></div>
    </div>
    <!--Venue -->
    <div class="form-group">
     <label for="inputVenue" class="col-sm-3 control-label">Venue*</label>
     <div class="col-sm-7">
      <%= f.text_field :venue,:class =>"form-control1", :id=>"venue_name",:placeholder => "Venue" %>
    </div>
    <div class="col-sm-2"></div>
  </div>
  <!--Date and Time -->
  <div class="form-group">
   <label for="inputDate" class="col-sm-3 control-label">Date*</label>
   <div class="col-sm-3">
    <%= f.text_field :date,:class =>"form-control1", :id=>"venue_name",:id =>"datepicker",:placeholder => "Date" %>
  </div>

  <label for="inputTime" class="col-sm-1 control-label">Time*</label>
  <div class="col-sm-3">
    <%= f.time_field :time,:class =>"form-control1", :id=>"event_time",:placeholder => "Time" %>
  </div>
</div>
<!--Description -->
<div class="form-group">
 <label for="inputescription" class="col-sm-3 control-label">Description*</label>
 <div class="col-sm-7">
  <%= f.text_area :description,:size=> "50x7",:class =>"form-control1", :id=>"venue_name",:placeholder => "Description" %>
</div>
<div class="col-sm-2"></div>
</div>
<!--Invitees -->
<div class="form-group">
 <label for="inputescription" class="col-sm-3 control-label">Invitees</label>
 <div class="col-sm-7" >
  <table class="tableCreateEvent table table-responsive table-fixed">
   <thead>
    <tr>

     <th class="col-sm-10"></th>
   </tr>
 </thead>
 <tbody style="border-style: solid;border-width: 1px;border-color: #ccc;">
   <% @users=User.all %>
   <% @users.each do |user|%>
   <% unless user.id==current_user.id %>
   <tr>
    <td><%= check_box_tag "invitees[]", user.id %></td>
    <td><%=user.name.titleize%></td>
  </tr>
  <%end%>

  <%end%>
</tbody>
</table>
</div>
<div class="col-sm-2"></div>
</div>

<!--Status -->
<div class="form-group">
 <label for="inputstatus" class="col-sm-3 control-label">Status</label>
 <div class="col-sm-3">
  <%= f.select :status, options_for_select([['Open', 'open'], ['Close', 'close']]),{}, {class: 'form-control1'}  %>
</div>
<div class="col-sm-2"></div>
</div>
<div class="modal-footer">
  <%= f.submit "Ok", :class=>"btn btn-primary ok-btn-padding", :id =>"signup_button"%>
  <button type="button" class="btn btn-default ok-btn-padding" data-dismiss="modal">Cancel</button>
</div>
<%end%>
</div>
</div>
<!-- ./ Moodel body -->
</div>

</div>
</div>
</div>

app/views/events/_ticket.html.erb
   <!--List view begin -->
   <div class="event-panels">
     <div class="row">
      <div class="col-sm-2">
       <div class="order-number"></div>
     </div>
     <div class="col-sm-10">
       <div class="event-title">
       <b style="color:#4cae4c; text-transform:none" >Event&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;</b>
       <%=event.event_name%></div>
       <div class="organiser">
       <b style="color:#4cae4c; font-size: 16px;">Organiser&nbsp;:&nbsp;&nbsp;</b>
       <%=event.user.name.titleize%></div>
       <!-- Participant button-->     
       <div class="participants">
         
         <%= link_to "Participants", event_path(event), remote: true %>
         <%if event.status=="open"%>
         <span class="badge pull-right">Open</span>
         <%else event.status=="close"%>
         <span class="badge closed pull-right">Close</span>
         <% end %>
       </div>
     </div>
   </div>
 </div>

app/views/events/edit.js.erb
$('#div_event_details').html("<%= escape_javascript(render(:partial=>'events/create_event',:locals=>{:participants=>@participants,:users=>@users,:notparticipants=>@user})) %>");

app/views/events/index.html.erb
<!--    Header-->
<%= render :partial => "layouts/common/header"%>
<div id="div_flash_message">
  <%= render :partial=>"/layouts/common/flash_message" %>
</div>
<!--Content Area-->
<div class="container">
  <div class="row"> 
    <div class="col-sm-12">
     <!--Create Button trigger modal -->
     <div class="well-sm pull-right">
       <%= button_to "Create New Event", new_event_path ,:method=> :get, remote: true, :class=>"btn btn-warning", 'data-toggle' => 'modal'%>
       
     </div>
     <!-- Modal -->
     <div class="modal fade" id="myCreate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      
      <%= render :partial => "events/create_event_modal"%>

      <!-- </div> -->
      <div class="clearfix"></div>
      <!-- </div> -->
      <div class="row"> 
       <!--List View column -->
       <div class="col-sm-5"> 
         <%if @events.present?%>
         <%@events.each do|event|%>
         <%= link_to edit_event_path(event), remote: true do %>
         <%= render :partial => "events/ticket",:locals=>{:event=>event} %>
         <%end%>
         <%end%>
         <%= paginate @events %>
         <%else%>
         <div class="jumbotron">
          <h4 ><center>No events created</center></h4>
        </div>
        <%end%>

      </div>
      
      <!-- ./List view -->

      <!--Show View item -->
      <div class="col-sm-7">
        <div id="div_event_details">
          <%if @events.present?%>
          <%= render :partial => "events/create_event",:locals=>{:participants=>@participants,:users=>@users,:notparticipants=>@user}%> 
          <%else%>
          <div class="jumbotron">
            <h4><center>Start new event by clicking [Create new event]</center></h4>
          </div>
          <%end%>
        </div>
      </div>
      <!-- ./ Show item --> 

    </div>

  </div>

app/views/events/new.js.erb
$('#popup_modal').html("<%= escape_javascript(render(:partial=>'events/create_event_modal')) %>");
$('#popup_modal').modal("show")
validateEventForm();

app/views/events/show.js.erb
$('#popup_modal').html("<%= escape_javascript(render(:partial=>'events/participants', :locals=>{:participants=>@participants,:users=>@users,:invitee=>@invitee})) %>");
$('#popup_modal').modal("show")

app/views/layouts/_signin_modal.html.erb
<div  id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Log In</h4>
			</div>
			<%= form_tag sessions_path , :class =>"form-horizontal", :id =>"signin_user", :remote=> true, :method=> :post do |f| %>
			<div class="modal-body">
				<div class="form-group">
					<label for="inputEmail" class="col-sm-3 control-label">Email id</label>
					<div class="col-sm-7">
						<%= text_field_tag :email,nil,:class =>"form-control", :id=>"inputEmail",:placeholder => "Email Address" %>    
					</div>
					<div class="col-sm-2"></div>
				</div>
				<div class="form-group">
					<label for="inputPassword" class="col-sm-3 control-label">Password</label>
					<div class="col-sm-7">
						<%= password_field_tag :password,nil,:class =>"form-control", :id=>"inputPassword",:placeholder => "Password" %>
					</div>
					<div class="col-sm-2"></div>
				</div>
			</div>
			<div class="modal-footer">
				<%= submit_tag "Ok", :class=>"btn btn-primary ok-btn-padding", :id =>"signup_button"%>
				<button type="button" class="btn btn-default ok-btn-padding" data-dismiss="modal">Cancel</button>
				<br></br>
				<center><%= link_to "Login with Twitter", "/auth/twitter", id: "sign_in" %></center>
			</div>
			<%end%>
		</div>
	</div>
</div>

app/views/layouts/_signup_modal.html.erb
<!--Sign up Modal -->

<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title">Sign Up</h4>
    </div>
    <%= form_for :user, :url => users_path, :method=> 'post',:remote => true,:html => {:class =>"form-horizontal",:id =>"form_user"} do |f| %>
    <div class="modal-body">
      <div class="form-group">
        <%= f.label "Name*", :class=>"col-sm-3 control-label",:required => true %>
        <div class="col-sm-7">
          <%= f.text_field :name,:class =>"form-control", :id=>"signup_name",:placeholder => "Name" %>
        </div>
        <div class="col-sm-2"></div>
      </div>
      <div class="form-group">
        <%= f.label "Email*", :class=>"col-sm-3 control-label",:required =>true %>
        <div class="col-sm-7">
          <%= f.text_field :email,:class =>"form-control", :id=>"user_email",:placeholder => "Email" %>
        </div>
        <div class="col-sm-2"></div>
      </div>
      <div class="form-group">
        <%= f.label "Password*", :class=>"col-sm-3 control-label" %>
        <div class="col-sm-7">
          <%= f.password_field :password,:class =>"form-control", :id=>"signup_password",:placeholder => "Password" %>
        </div>
        <div class="col-sm-2"></div>
      </div>
      <div class="form-group">
        <%= f.label "Confirm*", :class=>"col-sm-3 control-label" %>
        <div class="col-sm-7">
          <%= f.password_field :password_confirmation,:class =>"form-control", :id=>"signup_confirm_password",:placeholder => "Confirm Password" %>
        </div>
        <div class="col-sm-2"></div>
      </div>
      <div class="form-group">
        <label for="inputstatus" class="col-sm-3 control-label">Profile Pic</label>
        <div class="col-sm-3">
          <div class="event-title">
            <%= image_tag "Profile-Pic.jpg", :alt=>"image", :class=>"img-thumbnail", :id => "preview" %>
          </div>
        </div>
        <div class="col-sm-3">
          <%= f.file_field :image, :id=>"exampleInputFile" %>
        </div>
        <div class="col-sm-2"></div>
      </div>
    </div>
    <div class="modal-footer">
      <%= f.submit "Ok", :class=>"btn btn-primary ok-btn-padding", :id =>"signup_button"%>
      <button type="button" class="btn btn-default ok-btn-padding" data-dismiss="modal">Cancel</button>
    </div>
    <%end%>
  </div>
</div>
</div>

app/views/layouts/common/_header.html.erb
<nav class="navbar navbar-inverse ">
  <div class="container">
    <div class="navbar-header">
      <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Event Scheduler",root_path,:class =>"navbar-brand" %>
    </div>

    <div class="navbar-collapse collapse">
      

     <% if current_user.present? %>
     <div class="navbar-collapse collapse">
       <ul class="nav navbar-nav navbar-right">
       <li>
        <%= image_tag  current_user.image,  :alt =>"Image", :class => "img-rounded profile-pic" %>
           <span class="profile-name"><%= current_user.name.titleize %></span></li>
           <li> 
             <%= button_to "Sign Out",sessions_destroy_path, :class => "btn btn-success signup-login-btn", :method => :delete %>
           </li>

         </ul>
       </div>
       <% else %>


       
       <ul class="nav navbar-nav navbar-right">
         <li>
          <%= button_to "Sign up", new_user_path ,:method=> :get, remote: true, :class=>"btn btn-success signup-login-btn", 'data-toggle' => 'modal', 'data-target'=>'#myModal'%>
        </li>
        <li>
          <%= button_to "Log In", new_session_path ,:method=> :get, remote: true, :class=>"btn btn-success signup-login-btn", 'data-toggle' => 'modal', 'data-target'=>'#myModal'%>


        </li>

      </ul>
      <% end %>
    </div><!--/.navbar-collapse -->
  </div>

</nav>

app/views/update_mail/update_event.html.erb
<html>
<head>
	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
	<p>Hi, <%= @user.name %>!</p>
	<p>The event <%=@event.event_name%> has been edited</p>
	<p>
	<b>Date</b>:<%=@date%><br>
	<b>Time</b>:<%=@time%><br>
	<b>Description</b>:<%=@description%><br>
	. Please send your response 
	<%= link_to "Yes", email_response_event_url(@invitee,:response => "yes")%>
	<%= link_to "No", email_response_event_url(@invitee ,:response => "no")%>

	</p>
</body>
</html>

app/views/users/new.js.erb
$('#popup_modal').html("<%= escape_javascript(render(:partial=>'layouts/signup_modal')) %>");
$('#popup_modal').modal("show")
validateUserForm();